modLoader="neoforge"
loaderVersion="[2,)"
license="All Rights Reserved"

[[mods]]
modId="teleportpay"
version="1.0.0"
displayName="TeleportPay"
description='''Teleportiere dich zu Koordinaten gegen Diamantkosten!'''